import { chmodSync, closeSync, fsyncSync, openSync, statSync } from "node:fs";

export class ServicePermissionError extends Error {}
export function assertPrivateMode(path: string, expected: number): void { if (process.platform !== "win32" && (statSync(path).mode & 0o777) !== expected) throw new ServicePermissionError("POSIX_PRIVATE_MODE"); }
export function assertWindowsAclPrivate(principals: readonly string[], currentUser: string): void { const normalizedUser = currentUser.trim().toUpperCase(); const allowed = (principal: string) => { const value = principal.trim().toUpperCase(); return value === normalizedUser || value.endsWith(`\\${normalizedUser}`) || value === "SYSTEM" || value === "NT AUTHORITY\\SYSTEM" || value === "NT\\SISTEMA" || /^AUTHORITY\\LOGONSESSIONID_[A-Z0-9_]+$/.test(value); }; if (!principals.length || principals.some(principal => !allowed(principal))) throw new ServicePermissionError("WINDOWS_FOREIGN_PRINCIPAL"); }
function restrictWindows(path: string): void { const currentUser = process.env.USERNAME; if (!currentUser) throw new ServicePermissionError("WINDOWS_CURRENT_USER_UNAVAILABLE"); const result = Bun.spawnSync(["icacls", path, "/inheritance:r", "/grant:r", `${currentUser}:(F)`], { stdout: "pipe", stderr: "pipe" }); if (result.exitCode !== 0) throw new ServicePermissionError("WINDOWS_ACL_SET"); const inspection = Bun.spawnSync(["icacls", path], { stdout: "pipe", stderr: "pipe" }); if (inspection.exitCode !== 0) throw new ServicePermissionError("WINDOWS_ACL_READ"); const output = new TextDecoder().decode(inspection.stdout); const principals = output.split(/\r?\n/).map(line => line.match(/\s([^\s]+):\([^)]*\)\s*$/)?.[1]).filter((value): value is string => Boolean(value)); assertWindowsAclPrivate(principals, currentUser); }
export function restrictDirectory(path: string): void { if (process.platform === "win32") restrictWindows(path); else { chmodSync(path, 0o700); assertPrivateMode(path, 0o700); } }
export function restrictFile(path: string): void { if (process.platform === "win32") restrictWindows(path); else { chmodSync(path, 0o600); assertPrivateMode(path, 0o600); } }
export function fsyncDirectory(path: string): void { let descriptor: number | undefined; try { descriptor = openSync(path, "r"); try { fsyncSync(descriptor); } catch (cause) { const code = (cause as NodeJS.ErrnoException).code; if (process.platform !== "win32" || !["EPERM", "EINVAL", "EBADF"].includes(code ?? "")) throw cause; } } finally { if (descriptor !== undefined) closeSync(descriptor); } }
