import type { ServiceConfigV1, ServiceInstanceV1, ServiceLockOwnerV1, ServiceStopRequestV1 } from "./types.ts";

export class ServiceSchemaError extends Error {}
const digest = (value: unknown): value is `sha256:${string}` => typeof value === "string" && /^sha256:[a-f0-9]{64}$/.test(value);
const uuid = (value: unknown): value is string => typeof value === "string" && /^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(value);
const timestamp = (value: unknown): value is string => typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(value) && !Number.isNaN(Date.parse(value));
const object = (value: unknown, keys: readonly string[]): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new ServiceSchemaError("OBJECT_EXPECTED"); const actual = Object.keys(value); if (actual.length !== keys.length || actual.some(key => !keys.includes(key))) throw new ServiceSchemaError("CLOSED_OBJECT"); return value as Record<string, unknown>; };
const optionalObject = (value: unknown, required: readonly string[], optional: readonly string[] = []): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new ServiceSchemaError("OBJECT_EXPECTED"); const actual = Object.keys(value), allowed = [...required, ...optional]; if (actual.some(key => !allowed.includes(key)) || required.some(key => !(key in (value as object)))) throw new ServiceSchemaError("CLOSED_OBJECT"); return value as Record<string, unknown>; };
const port = (value: unknown): value is number => typeof value === "number" && Number.isInteger(value) && value >= 1024 && value <= 65535;
const positive = (value: unknown): value is number => typeof value === "number" && Number.isInteger(value) && value >= 1;
const timeWindow = (created: unknown, expires: unknown) => { if (!timestamp(created) || !timestamp(expires) || Date.parse(expires) <= Date.parse(created) || Date.parse(expires) - Date.parse(created) > 30_000) throw new ServiceSchemaError("INVALID_TIME_WINDOW"); };

export function validateServiceConfig(value: unknown): ServiceConfigV1 { const raw = optionalObject(value, ["schema_version", "scope", "host", "port", "read_only", "lifetime", "no_open"], ["project_root", "project_root_digest"]); if (raw.schema_version !== "1.0.0" || raw.host !== "127.0.0.1" || !port(raw.port) || raw.read_only !== true || raw.lifetime !== "persistent" || raw.no_open !== true) throw new ServiceSchemaError("INVALID_CONFIG"); if (raw.scope === "global") { if ("project_root" in raw || "project_root_digest" in raw) throw new ServiceSchemaError("GLOBAL_PROJECT_FIELDS"); return raw as ServiceConfigV1; } if (raw.scope !== "project" || typeof raw.project_root !== "string" || raw.project_root.length < 1 || raw.project_root.length > 1024 || !digest(raw.project_root_digest)) throw new ServiceSchemaError("INVALID_PROJECT_CONFIG"); return raw as ServiceConfigV1; }
export function validateInstance(value: unknown): ServiceInstanceV1 { const raw = optionalObject(value, ["schema_version", "instance_id", "pid", "state", "started_at", "config_digest", "process_digest", "control_secret_ref", "control_secret_digest", "log_ref"], ["last_restart"]); if (raw.schema_version !== "1.0.0" || !uuid(raw.instance_id) || !positive(raw.pid) || !["starting", "running", "stopping", "error"].includes(raw.state as string) || !timestamp(raw.started_at) || !digest(raw.config_digest) || !digest(raw.process_digest) || typeof raw.control_secret_ref !== "string" || !new RegExp("^secrets/[a-f0-9-]{36}\\.control$").test(raw.control_secret_ref) || !digest(raw.control_secret_digest) || typeof raw.log_ref !== "string" || !/^logs\/[A-Za-z0-9._-]{1,128}\.log$/.test(raw.log_ref)) throw new ServiceSchemaError("INVALID_INSTANCE"); if (raw.last_restart !== undefined) { const restart = object(raw.last_restart, ["attempted_at", "requested_config_digest", "effective_config_digest", "rollback_state"]); if (!timestamp(restart.attempted_at) || !digest(restart.requested_config_digest) || !digest(restart.effective_config_digest) || !["not_needed", "restored_previous", "restore_failed"].includes(restart.rollback_state as string)) throw new ServiceSchemaError("INVALID_RESTART"); } return raw as ServiceInstanceV1; }
export function validateLockOwner(value: unknown): ServiceLockOwnerV1 { const raw = object(value, ["schema_version", "owner_id", "manager_pid", "operation", "target", "acquired_at", "expires_at", "token_ref", "token_digest"]); const target = optionalObject(raw.target, ["nirvana_home_digest", "scope", "port"], ["project_root_digest"]); if (raw.schema_version !== "1.0.0" || !uuid(raw.owner_id) || !positive(raw.manager_pid) || !["start", "stop", "restart"].includes(raw.operation as string) || !digest(target.nirvana_home_digest) || !port(target.port) || typeof raw.token_ref !== "string" || !new RegExp("^secrets/[a-f0-9-]{36}\\.manager$").test(raw.token_ref) || !digest(raw.token_digest)) throw new ServiceSchemaError("INVALID_OWNER"); if (target.scope === "global") { if ("project_root_digest" in target) throw new ServiceSchemaError("GLOBAL_PROJECT_DIGEST"); } else if (target.scope !== "project" || !digest(target.project_root_digest)) throw new ServiceSchemaError("PROJECT_DIGEST_REQUIRED"); timeWindow(raw.acquired_at, raw.expires_at); return raw as ServiceLockOwnerV1; }
export function validateStopRequest(value: unknown): ServiceStopRequestV1 { const raw = object(value, ["schema_version", "request_id", "instance_id", "action", "created_at", "expires_at", "nonce_ref", "nonce_digest", "auth_algorithm", "auth_tag"]); if (raw.schema_version !== "1.0.0" || !uuid(raw.request_id) || !uuid(raw.instance_id) || raw.action !== "stop" || typeof raw.nonce_ref !== "string" || !new RegExp("^control/nonces/[a-f0-9-]{36}\\.nonce$").test(raw.nonce_ref) || !digest(raw.nonce_digest) || raw.auth_algorithm !== "hmac-sha256" || typeof raw.auth_tag !== "string" || !/^[a-f0-9]{64}$/.test(raw.auth_tag)) throw new ServiceSchemaError("INVALID_STOP_REQUEST"); timeWindow(raw.created_at, raw.expires_at); return raw as ServiceStopRequestV1; }
