/**
 * Registry loader for harness.
 *
 * Reads:
 *   ~/.squads-registry.json    (preferred)  — generated by squads skill
 *   ~/.squads-registry-v5.json (fallback)   — older v5 path
 *   ~/.businesses-registry.json             — generated by businesses skill
 *
 * Returns empty stubs + warnings when files are missing or malformed, so the
 * harness still loads in a fresh install where no skill has indexed yet.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const PATHS = require(path.join(__dirname, '..', '..', '_shared', 'lib', 'paths.js'));

const SQUADS_PATHS = [
  PATHS.SQUADS_REGISTRY_PATH,
  path.join(PATHS.HOME, '.squads-registry-v5.json'),  // legacy fallback
];
const BUSINESSES_PATH = PATHS.BUSINESSES_REGISTRY_PATH;

/**
 * Read and parse a JSON file, returning {ok, data, error}.
 */
function readJson(p) {
  try {
    if (!fs.existsSync(p)) return { ok: false, error: 'not_found', path: p };
    const raw = fs.readFileSync(p, 'utf8');
    if (!raw.trim()) return { ok: false, error: 'empty_file', path: p };
    return { ok: true, data: JSON.parse(raw), path: p };
  } catch (e) {
    return { ok: false, error: e.message, path: p };
  }
}

/**
 * Load squads registry, trying each known path in order.
 * @returns {{registry: object, warnings: string[]}}
 */
function loadSquads() {
  const warnings = [];
  for (const p of SQUADS_PATHS) {
    const r = readJson(p);
    if (r.ok) {
      // Lightweight shape check
      if (typeof r.data !== 'object' || r.data === null) {
        warnings.push(`squads registry at ${p} is not an object; ignoring`);
        continue;
      }
      if (!r.data.capabilities && !r.data.squads) {
        warnings.push(`squads registry at ${p} has neither 'capabilities' nor 'squads' field; treating as empty`);
      }
      return {
        registry: {
          schema_version: r.data.schema_version || '1.0.0',
          host_protocol_version: r.data.host_protocol_version || '5.0',
          squads: r.data.squads || {},
          capabilities: r.data.capabilities || {},
          domains: r.data.domains || {},
          // Extra non-schema field — v4 squads inferred capabilities propagated
          // to harness Stage 2 BM25 (ver router.js#buildMatchDocs).
          _v4_inferred_capabilities: r.data._v4_inferred_capabilities || {},
          source_path: r.path,
        },
        warnings,
      };
    } else if (r.error !== 'not_found') {
      warnings.push(`squads registry at ${p}: ${r.error}`);
    }
  }
  warnings.push(`squads registry not found at any of: ${SQUADS_PATHS.join(', ')} — operating with empty registry`);
  return {
    registry: {
      schema_version: '1.0.0',
      host_protocol_version: '5.0',
      squads: {},
      capabilities: {},
      domains: {},
      _v4_inferred_capabilities: {},
      source_path: null,
    },
    warnings,
  };
}

/**
 * Load businesses registry.
 * @returns {{registry: object, warnings: string[]}}
 */
function loadBusinesses() {
  const warnings = [];
  const r = readJson(BUSINESSES_PATH);
  if (r.ok) {
    if (typeof r.data !== 'object' || r.data === null || !r.data.businesses) {
      warnings.push(`businesses registry at ${BUSINESSES_PATH} missing 'businesses' field; treating as empty`);
      return {
        registry: { schema_version: '1.0.0', businesses: {}, source_path: r.path },
        warnings,
      };
    }
    return {
      registry: {
        schema_version: r.data.schema_version || '1.0.0',
        businesses: r.data.businesses,
        // Extra non-schema fields propagated to consumers (Stage 0 etc.)
        _business_routing: r.data._business_routing || {},
        _invalid_entries: r.data._invalid_entries || [],
        source_path: r.path,
      },
      warnings,
    };
  }
  if (r.error !== 'not_found') {
    warnings.push(`businesses registry at ${BUSINESSES_PATH}: ${r.error}`);
  } else {
    warnings.push(`businesses registry not found at ${BUSINESSES_PATH} — operating with empty registry`);
  }
  return {
    registry: { schema_version: '1.0.0', businesses: {}, _business_routing: {}, source_path: null },
    warnings,
  };
}

/**
 * Convenience: load both registries.
 * @returns {{squads: object, businesses: object, warnings: string[]}}
 */
function loadAll() {
  const s = loadSquads();
  const b = loadBusinesses();
  return {
    squads: s.registry,
    businesses: b.registry,
    warnings: [...s.warnings, ...b.warnings],
  };
}

module.exports = { loadAll, loadSquads, loadBusinesses, SQUADS_PATHS, BUSINESSES_PATH };
