// routing-cards.ts — the compiled cards the `cards` routing mode reads.
//
// One line per business and per squad, and the line states what the entity
// PRODUCES before what it is about. A brief names its theme ("a startup in the
// legal market"); the card has to answer with the object ("software"). Theme
// overlap is what misroutes, so the object comes first and the description is
// clipped short.
//
// Mind-clones are not carded: the cards router receives the handful the
// lexical clone search ranks for the brief, never the whole library.
//
// Written by scripts/build-routing-digest.ts beside the digest, from the same
// registries in the same pass, so `nrv index` and the staleness rebuild keep
// the two in step.

/** File-format suffixes in `produces` ids ("warmup-schedule-csv",
 *  "avatar-profile.md"): the object is the schedule or the profile, the format
 *  is an implementation detail of the squad. */
const FORMAT_SUFFIX = /[-.](md|json|jsonl|csv|yaml|yml|html|pdf|txt|png|jpg|svg|mp4|mp3|wav|zip|pptx|docx|xlsx)$/i;

export interface CardsInput {
  businesses: Record<string, any>;
  squads: Record<string, any>;
  /** capability id → provider entries ({ squad, not_for?, ... }) */
  capabilities: Record<string, any[]>;
}

/** One-line sanitizer: a pipe would break the card grammar, a newline the line. */
const flat = (value: unknown): string => String(value ?? "").replace(/\|/g, "/").replace(/\s+/g, " ").trim();

const strList = (value: unknown): string[] =>
  Array.isArray(value) ? value.filter((x): x is string => typeof x === "string" && x.trim().length > 0).map(flat) : [];

function unique(items: string[], limit: number): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of items) {
    const key = item.toLowerCase();
    if (!item || seen.has(key)) continue;
    seen.add(key);
    out.push(item);
    if (out.length === limit) break;
  }
  return out;
}

/** Clip at a sentence end when one sits in the last 40%, else at a word. */
export function clip(text: string, max: number): string {
  if (text.length <= max) return text;
  const cut = text.slice(0, max);
  const sentence = cut.lastIndexOf(". ");
  if (sentence > max * 0.6) return cut.slice(0, sentence + 1);
  const space = cut.lastIndexOf(" ");
  return `${cut.slice(0, space > 0 ? space : max)}…`;
}

function products(items: string[]): string[] {
  return unique(items.map((item) => item.replace(FORMAT_SUFFIX, "")), 6);
}

function line(id: string, produces: string[], summary: string, notFor: string[]): string {
  const parts = [id];
  if (produces.length) parts.push(`produces: ${produces.join(", ")}`);
  if (summary) parts.push(summary);
  if (notFor.length) parts.push(`not: ${notFor.join("; ")}`);
  return parts.join(" | ");
}

export function businessCard(slug: string, business: any): string {
  return line(
    `business:${slug}`,
    products(strList(business?.produces)),
    clip(flat(business?.description), 120),
    unique(strList(business?.not_for), 2),
  );
}

/** A squad has no `not_for` of its own in the registry; its capabilities do. */
export function squadCard(slug: string, squad: any, capabilities: Record<string, any[]>): string {
  const notFor: string[] = [];
  for (const id of strList(squad?.capabilities)) {
    const provider = (capabilities[id] || []).find((p) => p?.squad === slug);
    notFor.push(...strList(provider?.not_for));
  }
  return line(
    `squad:${slug}`,
    products(strList(squad?.produces)),
    clip(flat(squad?.description), 120),
    unique(notFor, 2),
  );
}

export function renderRoutingCards(input: CardsInput, generatedAt: string = new Date().toISOString()): string {
  const businesses = Object.keys(input.businesses).sort();
  const squads = Object.keys(input.squads).sort();
  return [
    "# Nirvana-OS routing cards",
    "# Generated by harness/scripts/build-routing-digest.ts — do not edit by hand.",
    `generated_at: ${generatedAt}`,
    "One line per business and squad: id | produces: what it delivers | what it is | not: what it does not do.",
    "",
    "## Businesses",
    ...businesses.map((slug) => businessCard(slug, input.businesses[slug])),
    "",
    "## Squads",
    ...squads.map((slug) => squadCard(slug, input.squads[slug], input.capabilities)),
    "",
  ].join("\n");
}
