// runtime-install.ts — how a skill lands in a runtime's skills directory, and
// where the shared dependency store is linked so scripts inside it still resolve.
//
// The rule this file enforces: NO `node_modules` inside a skills root. Codex's
// skill loader (codex-rs/ext/skills/src/loader/discovery.rs, 0.153) walks every
// skills root breadth-first, FOLLOWS directory symlinks, prunes only hidden
// directories, and gives up after 20,000 entries per root. The installer used to
// drop a `node_modules -> ~/.nirvana/node_modules` symlink inside every copied
// skill so `bun ~/.codex/skills/<s>/scripts/x.ts` could resolve its imports; the
// loader followed that link into the whole dependency store, hit the limit on
// every run ("skills scan reached its traversal limit"), and shortened skill
// descriptions to fit its budget. Measured 2026-09-05: 191,524 files under
// ~/.codex/skills, of which the engine's own skills were a few thousand.
//
// Module resolution only needs a `node_modules` somewhere on the walk UP from
// the script's real path. So the link goes one level ABOVE the skills root
// (`~/.codex/node_modules`, `~/.claude/node_modules`, …), which no loader
// treats as a skill tree, and never inside it. Symlinked skills (Mac/Linux
// runtimes, ~/.agents/skills) resolve through `~/.nirvana/skills/node_modules`,
// because Bun resolves the entry to its real path before walking up.
import { cpSync, existsSync, lstatSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { COPY_MARKER } from "./runtime-dirs.ts";

/** Where a runtime's dependency link lives: beside the skills root, never in it. */
export function depsLinkFor(skillsDir: string): string {
  return join(dirname(skillsDir), "node_modules");
}

function isSymlink(p: string): boolean {
  try { return lstatSync(p).isSymbolicLink(); } catch { return false; }
}

/**
 * Point `linkPath` at the shared store. Replaces a previous link; never touches
 * a REAL directory — a tree somebody installed by hand is theirs to remove, and
 * `nrv deps status` reports it. Returns what happened, for the installer's log.
 */
export function ensureDepsLink(linkPath: string, store: string, isWindows = process.platform === "win32"): "linked" | "kept-real-dir" | "no-store" {
  if (!existsSync(store)) return "no-store";
  if (isSymlink(linkPath)) rmSync(linkPath, { force: true });
  else if (existsSync(linkPath)) return "kept-real-dir";
  mkdirSync(dirname(linkPath), { recursive: true });
  symlinkSync(store, linkPath, isWindows ? "junction" : undefined);
  return "linked";
}

/** Remove a `node_modules` SYMLINK directly under `dir`. A real directory stays. */
export function pruneDepsLinkInside(dir: string): boolean {
  const nm = join(dir, "node_modules");
  if (!isSymlink(nm)) return false;
  rmSync(nm, { force: true });
  return true;
}

/**
 * Copy one skill into a runtime directory: everything but `node_modules`, plus
 * the marker that lets a later install or uninstall recognise the copy as ours.
 * Nothing named `node_modules` is created inside the copy.
 */
export function materializeRuntimeSkillCopy(target: string, linkPath: string): void {
  cpSync(target, linkPath, { recursive: true, dereference: false, filter: (s) => basename(s) !== "node_modules" });
  writeFileSync(join(linkPath, COPY_MARKER), "Copy of ~/.nirvana/skills regenerated by `nrv install`. Edit the source, not this.\n");
}
