// generated-schema-parity.test.ts — the JSON Schemas in _shared/schemas are
// GENERATED from validators.ts, and the committed files match the generator.
//
// The bug this closes is documented drift: `capability.schema.json` capped
// `description` at 500 chars for months after LIMITS raised it to 1500, and
// `skills/squads/schemas/squad-schema.json` described a v4 manifest nobody
// authored any more. `bun scripts/gen-json-schemas.ts --check` is wired into
// `check:all`; this test is the same gate at test speed, plus the two facts a
// diff alone would not state — that the three files exist, and that the
// hand-maintained per-squad mirrors are gone.
import { describe, expect, test } from "bun:test";
import * as fs from "node:fs";
import * as path from "node:path";
import { spawnSync } from "node:child_process";
import { z } from "zod";
import { CapabilitySchema, SquadManifestSchema, WorkflowSchema } from "../validators/validators.ts";
import { spawnBudgetMs } from "../../harness/tests/helpers/test-budgets.ts";
import { makeTempRoot, removeDir } from "../../harness/tests/helpers/temp-dirs.ts";

const REPO = path.resolve(import.meta.dir, "..", "..", "..");
const SCHEMAS = path.join(REPO, "skills", "_shared", "schemas");
const read = (file: string) => JSON.parse(fs.readFileSync(path.join(SCHEMAS, file), "utf8"));

describe("the generator is the source of the files", () => {
  test("--check passes against the committed schemas", () => {
    const r = spawnSync(process.execPath, [path.join(REPO, "scripts", "gen-json-schemas.ts"), "--check"], { encoding: "utf8" });
    expect(r.stdout + r.stderr).toContain("JSON schema parity OK");
    expect(r.status).toBe(0);
  }, spawnBudgetMs(2));

  for (const [file, schema] of [
    ["capability.schema.json", CapabilitySchema],
    ["squad.schema.json", SquadManifestSchema],
    ["workflow.schema.json", WorkflowSchema],
  ] as Array<[string, z.ZodType]>) {
    test(`${file} is byte-identical to z.toJSONSchema of its Zod schema`, () => {
      const committed = read(file);
      const generated = z.toJSONSchema(schema, { unrepresentable: "any" }) as Record<string, unknown>;
      expect(committed.$comment).toContain("GENERATED by scripts/gen-json-schemas.ts");
      const { $schema, $id, title, description, $comment, ...body } = committed;
      const { $schema: _s, ...expected } = generated;
      expect(body).toEqual(expected);
    });
  }
});

describe("the contract the files state", () => {
  test("capability description tracks LIMITS, not the old 500-char cap", () => {
    expect(read("capability.schema.json").properties.description.maxLength).toBe(1500);
  });

  test("the squad manifest accepts protocol 6.0", () => {
    expect(read("squad.schema.json").properties.protocol.enum).toContain("6.0");
  });

  test("the workflow document requires at least one step, each with an agent", () => {
    const wf = read("workflow.schema.json");
    expect(wf.properties.steps.minItems).toBe(1);
    expect(wf.properties.steps.items.required).toContain("agent");
    expect(wf.properties.name.pattern).toBe("^[a-z][a-z0-9_-]*$");
  });

  test("the hand-maintained per-squad mirrors are gone", () => {
    expect(fs.existsSync(path.join(REPO, "skills", "squads", "schemas"))).toBe(false);
  });
});

// The generated file is a distributable contract, and a contract may not carry
// the configuration of whoever ran the generator. `LIMITS` reaches
// CapabilitySchema and SquadManifestSchema through a cascade that reads
// NIRVANA_LIMIT_* env vars, <project>/.nirvana-limits.yaml and
// ~/.claude/nirvana-limits.yaml — three inputs that live outside the commit.
// Generating under two hostile configurations must land on the same bytes, and
// those bytes must be the committed ones.
describe("the generator does not read the generating machine", () => {
  const generate = (env: Record<string, string>) =>
    spawnSync(process.execPath, [path.join(REPO, "scripts", "gen-json-schemas.ts"), "--check"], {
      encoding: "utf8",
      env: { ...process.env, ...env },
    });

  test("an env override of a limit the schemas embed does not move the bytes", () => {
    const r = generate({
      NIRVANA_LIMIT_CAPABILITY_DESCRIPTION_MAX: "900",
      NIRVANA_LIMIT_CAPABILITY_KEYWORDS_MAX: "11",
      NIRVANA_LIMIT_SQUAD_CAPABILITIES_MAX: "13",
    });
    expect(r.stdout + r.stderr).toContain("JSON schema parity OK");
    expect(r.status).toBe(0);
  }, spawnBudgetMs(2));

  test("two different user override files produce the same bytes", () => {
    const roots = [
      { root: makeTempRoot("gen-limits-a-"), description: "700", capabilities: "17" },
      { root: makeTempRoot("gen-limits-b-"), description: "4000", capabilities: "37" },
    ];
    try {
      for (const { root, description, capabilities } of roots) {
        fs.mkdirSync(path.join(root, ".claude"), { recursive: true });
        fs.writeFileSync(
          path.join(root, ".claude", "nirvana-limits.yaml"),
          `capability_description_max: ${description}\nsquad_capabilities_max: ${capabilities}\n`,
          "utf8",
        );
        // os.homedir() reads HOME on POSIX and USERPROFILE on Windows.
        const r = generate({ HOME: root, USERPROFILE: root });
        expect(r.stdout + r.stderr).toContain("JSON schema parity OK");
        expect(r.status).toBe(0);
      }
    } finally {
      for (const { root } of roots) removeDir(root);
    }
  }, spawnBudgetMs(4));
});
