// generated-schema-parity.test.ts — the JSON Schemas in _shared/schemas are
// GENERATED from validators.ts, and the committed files match the generator.
//
// The bug this closes is documented drift: `capability.schema.json` capped
// `description` at 500 chars for months after LIMITS raised it to 1500, and
// `skills/squads/schemas/squad-schema.json` described a v4 manifest nobody
// authored any more. `bun scripts/gen-json-schemas.ts --check` is wired into
// `check:all`; this test is the same gate at test speed, plus the two facts a
// diff alone would not state — that the three files exist, and that the
// hand-maintained per-squad mirrors are gone.
import { describe, expect, test } from "bun:test";
import * as fs from "node:fs";
import * as path from "node:path";
import { spawnSync } from "node:child_process";
import { z } from "zod";
import { CapabilitySchema, SquadManifestSchema, WorkflowSchema } from "../validators/validators.ts";
import { spawnBudgetMs } from "../../harness/tests/helpers/test-budgets.ts";

const REPO = path.resolve(import.meta.dir, "..", "..", "..");
const SCHEMAS = path.join(REPO, "skills", "_shared", "schemas");
const read = (file: string) => JSON.parse(fs.readFileSync(path.join(SCHEMAS, file), "utf8"));

describe("the generator is the source of the files", () => {
  test("--check passes against the committed schemas", () => {
    const r = spawnSync(process.execPath, [path.join(REPO, "scripts", "gen-json-schemas.ts"), "--check"], { encoding: "utf8" });
    expect(r.stdout + r.stderr).toContain("JSON schema parity OK");
    expect(r.status).toBe(0);
  }, spawnBudgetMs(2));

  for (const [file, schema] of [
    ["capability.schema.json", CapabilitySchema],
    ["squad.schema.json", SquadManifestSchema],
    ["workflow.schema.json", WorkflowSchema],
  ] as Array<[string, z.ZodType]>) {
    test(`${file} is byte-identical to z.toJSONSchema of its Zod schema`, () => {
      const committed = read(file);
      const generated = z.toJSONSchema(schema, { unrepresentable: "any" }) as Record<string, unknown>;
      expect(committed.$comment).toContain("GENERATED by scripts/gen-json-schemas.ts");
      const { $schema, $id, title, description, $comment, ...body } = committed;
      const { $schema: _s, ...expected } = generated;
      expect(body).toEqual(expected);
    });
  }
});

describe("the contract the files state", () => {
  test("capability description tracks LIMITS, not the old 500-char cap", () => {
    expect(read("capability.schema.json").properties.description.maxLength).toBe(1500);
  });

  test("the squad manifest accepts protocol 6.0", () => {
    expect(read("squad.schema.json").properties.protocol.enum).toContain("6.0");
  });

  test("the workflow document requires at least one step, each with an agent", () => {
    const wf = read("workflow.schema.json");
    expect(wf.properties.steps.minItems).toBe(1);
    expect(wf.properties.steps.items.required).toContain("agent");
    expect(wf.properties.name.pattern).toBe("^[a-z][a-z0-9_-]*$");
  });

  test("the hand-maintained per-squad mirrors are gone", () => {
    expect(fs.existsSync(path.join(REPO, "skills", "squads", "schemas"))).toBe(false);
  });
});
