#!/usr/bin/env bun
/**
 * build-catalog.ts — what exists, for the orchestrator to read.
 *
 * Phase 3 Pass 1 surveys the whole library: every business and every squad, so
 * that nothing the machine owns can be invisible to the decision. This file is
 * what it reads, and it carries exactly two things per entity — the slug and
 * the FULL description.
 *
 * Why not less. The listing used to cut each description to its first sentence
 * capped at 96 characters, and 288 of this library's 292 entities were being
 * cut — routinely right where the prose stops naming the domain and starts
 * naming the work. Measured against 123 briefs that were dispatched, executed
 * and passed the gate, a keyword shortlist over that material missed the entity
 * that ACTUALLY DELIVERED in 47.9% of cases. The discriminating half was the
 * half being thrown away.
 *
 * Why not more. `produces`, `domains`, capability ids, versions and protocol
 * numbers add 27k tokens on this library and decide nothing at survey time:
 * they matter once a finalist is open, which is Pass 2, where there are five of
 * them instead of 292.
 *
 * Why a FILE and not two commands. A stable, sorted, deterministic file at a
 * fixed path is what a provider's prompt cache can hold across sessions.
 * Command output varies in ordering and scaffolding and caches badly. On a
 * maintainer-sized library (68 + 224) the survey is ~45k tokens; the file is
 * the difference between paying that once and paying it every run. On the
 * library a customer actually installs — the few entities that service needs —
 * it is a few thousand tokens and none of this matters.
 *
 *   nrv index            # writes it, with the registries
 *   bun build-catalog.ts --stdout
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { paths } from "../../_shared/lib/bun-helpers.ts";
const argv = process.argv.slice(2);
const toStdout = argv.includes("--stdout");

/** One entity: the slug, and everything its description says. */
function collect(root: string, manifest: string): Array<{ slug: string; description: string }> {
  let dirs: string[];
  try { dirs = fs.readdirSync(root, { withFileTypes: true }).filter(d => d.isDirectory()).map(d => d.name); }
  catch { return []; }
  const out: Array<{ slug: string; description: string }> = [];
  for (const slug of dirs) {
    try {
      // Parsed, never grepped: `description: >-` is a folded scalar and a grep
      // returns only its first physical line.
      const y = Bun.YAML.parse(fs.readFileSync(path.join(root, slug, manifest), "utf8")) as { description?: unknown } | null;
      const description = typeof y?.description === "string" ? y.description.replace(/\s+/g, " ").trim() : "";
      if (description) out.push({ slug, description });
    } catch { /* an entity that does not parse is reported by `nrv validate`, not here */ }
  }
  // Sorted, so the same library always produces byte-identical output and the
  // cache holds. Unsorted output re-costs the survey on every index.
  return out.sort((a, b) => a.slug.localeCompare(b.slug));
}

const businessesRoot = paths.BUSINESSES_DIR;
const squadsRoot = paths.SQUADS_DIR;
const businesses = collect(businessesRoot, "business.yaml");
const squads = collect(squadsRoot, "squad.yaml");

const lines: string[] = [
  "# Nirvana-OS catalog — what exists",
  "# Generated by harness/scripts/build-catalog.ts — do not edit by hand.",
  "# Slug and full description, nothing else. Open a finalist for the rest.",
  "",
  `## businesses (${businesses.length})`,
  "",
  ...businesses.map(b => `${b.slug} — ${b.description}`),
  "",
  `## squads (${squads.length})`,
  "",
  ...squads.map(s => `${s.slug} — ${s.description}`),
  "",
];
const text = lines.join("\n");

if (toStdout) {
  // NOT followed by process.exit(): exiting truncates the write at the pipe
  // buffer (128 KiB here, which cut every squad off and made two runs differ).
  process.stdout.write(text);
} else {

  const out = paths.CATALOG_PATH;
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, text);
  const tokens = Math.round(text.length / 4);
  console.log(`[build-catalog] ${businesses.length} businesses + ${squads.length} squads · ~${tokens} tokens · → ${out.replace(process.env.HOME || "", "~")}`);
}
