import { expect, test } from "bun:test";
import { chmodSync, closeSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { assertPrivateMode, assertWindowsAclPrivate, assertWindowsAclSids, cleanupPrivateFreshFile, createPrivateFreshFileTestHarness, openPrivateFreshFile, restrictFile } from "../lib/glance/service/permissions.ts";
import { resolveServiceRef } from "../lib/glance/service/paths.ts";
import { validateInstance, validateLockOwner, validateServiceConfig, validateStopRequest } from "../lib/glance/service/schema-validator.ts";
import { parseStrictJson } from "../lib/glance/service/strict-json.ts";
import { IncompatibleStateError, ServiceIoError, createPrivateWriteTestHarness, readStateFileOrArchive, readStateFileStrict, writeDurableJson, writePrivateBytes } from "../lib/glance/service/state.ts";
import { extractGlanceServiceSchemas, type SchemaExtractionIo } from "../../../scripts/extract-glance-service-schemas.ts";
import { createPrivateStateFixture } from "./helpers/glance-service-fixtures.ts";

const digest = `sha256:${"a".repeat(64)}`;
const uuid = "123e4567-e89b-12d3-a456-426614174000";
const timestamp = "2026-08-23T12:00:00.000Z";
const globalConfig = { schema_version: "1.0.0", scope: "global", host: "127.0.0.1", port: 3737, read_only: true, lifetime: "persistent", no_open: true };
const projectConfig = { ...globalConfig, scope: "project", project_root: "C:/work", project_root_digest: digest };
const instance = { schema_version: "1.0.0", instance_id: uuid, pid: 7, state: "running", started_at: timestamp, config_digest: digest, process_digest: digest, control_secret_ref: `secrets/${uuid}.control`, control_secret_digest: digest, log_ref: "logs/service.log" };
const owner = { schema_version: "1.0.0", owner_id: uuid, manager_pid: 7, operation: "start", target: { nirvana_home_digest: digest, scope: "global", port: 3737 }, acquired_at: timestamp, expires_at: "2026-08-23T12:00:01.000Z", token_ref: `secrets/${uuid}.manager`, token_digest: digest };
const stopRequest = { schema_version: "1.0.0", request_id: uuid, instance_id: uuid, action: "stop", created_at: timestamp, expires_at: "2026-08-23T12:00:01.000Z", nonce_ref: `control/nonces/${uuid}.nonce`, nonce_digest: digest, auth_algorithm: "hmac-sha256", auth_tag: "b".repeat(64) };
const changed = <T extends object>(value: T, property: string, replacement: unknown): T => ({ ...value, [property]: replacement });

test("SVC-CONFIG-GLOBAL-PASS", () => expect(validateServiceConfig(globalConfig)).toEqual(globalConfig));
test("SVC-CONFIG-GLOBAL-PROJECT", () => expect(validateServiceConfig(projectConfig)).toEqual(projectConfig));
test.each([["SVC-CONFIG-EXTRA", { ...globalConfig, extra: true }], ["SVC-CONFIG-HOST", changed(globalConfig, "host", "0.0.0.0")], ["SVC-CONFIG-LIFETIME", changed(globalConfig, "lifetime", "idle")], ["SVC-CONFIG-NO-OPEN", changed(globalConfig, "no_open", false)], ["SVC-CONFIG-PORT", changed(globalConfig, "port", 80)], ["SVC-CONFIG-READ-ONLY", changed(globalConfig, "read_only", false)], ["SVC-CONFIG-SCHEMA-VERSION", changed(globalConfig, "schema_version", "2.0.0")], ["SVC-CONFIG-SCOPE-ENUM", changed(globalConfig, "scope", "local")], ["SVC-CONFIG-PROJECT-MISSING", { ...projectConfig, project_root_digest: undefined }], ["SVC-CONFIG-PROJECT-DIGEST", changed(projectConfig, "project_root_digest", "sha256:ABC")], ["SVC-CONFIG-PROJECT-LENGTH", changed(projectConfig, "project_root", "x".repeat(1025))]])("%s rejects invalid config", (_id, value) => expect(() => validateServiceConfig(value)).toThrow());

test.each([["SVC-INSTANCE-CLOSED", { ...instance, unknown: true }], ["SVC-INSTANCE-CONFIG-DIGEST", changed(instance, "config_digest", "bad")], ["SVC-INSTANCE-LOG-REF", changed(instance, "log_ref", "../service.log")], ["SVC-INSTANCE-PID", changed(instance, "pid", 0)], ["SVC-INSTANCE-PROCESS-DIGEST", changed(instance, "process_digest", "bad")], ["SVC-INSTANCE-REF", changed(instance, "control_secret_ref", "secrets/not-a-uuid.control")], ["SVC-INSTANCE-REQUIRED", { ...instance, state: undefined }], ["SVC-INSTANCE-RESTART-CLOSED", { ...instance, last_restart: { attempted_at: timestamp, requested_config_digest: digest, effective_config_digest: digest, rollback_state: "not_needed", extra: true } }], ["SVC-INSTANCE-RESTART-ENUM", { ...instance, last_restart: { attempted_at: timestamp, requested_config_digest: digest, effective_config_digest: digest, rollback_state: "wrong" } }], ["SVC-INSTANCE-SECRET-DIGEST", changed(instance, "control_secret_digest", "bad")], ["SVC-INSTANCE-STATE", changed(instance, "state", "stopped")], ["SVC-INSTANCE-TIMESTAMP", changed(instance, "started_at", "tomorrow")], ["SVC-INSTANCE-UUID", changed(instance, "instance_id", "no")]])("%s rejects invalid instance", (_id, value) => expect(() => validateInstance(value)).toThrow());

test("SVC-OWNER-GLOBAL-PROJECT", () => expect(() => validateLockOwner({ ...owner, target: { ...owner.target, project_root_digest: digest } })).toThrow());
test("SVC-OWNER-TARGET-CLOSED", () => expect(() => validateLockOwner({ ...owner, target: { ...owner.target, extra: true } })).toThrow());
test("SVC-OWNER-OPERATION", () => expect(() => validateLockOwner(changed(owner, "operation", "status"))).toThrow());
test("SVC-OWNER-PROJECT-DIGEST", () => expect(() => validateLockOwner({ ...owner, target: { ...owner.target, scope: "project" } })).toThrow());
test("SVC-OWNER-TOKEN-REF", () => expect(() => validateLockOwner(changed(owner, "token_ref", "secrets/x.manager"))).toThrow());
test("SVC-OWNER-WINDOW", () => expect(() => validateLockOwner({ ...owner, expires_at: "2026-08-23T12:00:31.000Z" })).toThrow());
test("SVC-OWNER-UUID", () => expect(() => validateLockOwner(changed(owner, "owner_id", "bad"))).toThrow());
test("SVC-STOP-REQUEST-CLOSED", () => expect(() => validateStopRequest({ ...stopRequest, extra: true })).toThrow());
test("SVC-STOP-REQUEST-WINDOW", () => expect(() => validateStopRequest({ ...stopRequest, expires_at: "2026-08-23T12:00:31.000Z" })).toThrow());
test("SVC-STOP-REQUEST-NONCE", () => expect(() => validateStopRequest(changed(stopRequest, "nonce_ref", "control/nonces/bad.nonce"))).toThrow());
test("SVC-STRICT-JSON-DUPLICATE", () => expect(() => parseStrictJson(new TextEncoder().encode('{"a":1,"a":2}'))).toThrow());
test("SVC-STRICT-JSON-TRAILING", () => expect(() => parseStrictJson(new TextEncoder().encode('{} trailing'))).toThrow());

test.each([["SVC-PATH-TRAVERSAL", "../instance.json"], ["SVC-PATH-POSIX-ABS", "/instance.json"], ["SVC-PATH-WINDOWS-ABS", "C:\\instance.json"], ["SVC-PATH-ADS", "instance.json:secret"]])("%s rejects unsafe reference", (_id, ref) => { const root = mkdtempSync(join(tmpdir(), "glance-path-")); try { expect(() => resolveServiceRef(root, ref, false)).toThrow(); } finally { rmSync(root, { recursive: true, force: true }); } });
test("SVC-PATH-SYMLINK", () => { const root = mkdtempSync(join(tmpdir(), "glance-path-")); try { mkdirSync(join(root, "secrets")); symlinkSync(tmpdir(), join(root, "secrets", "link"), "junction"); expect(() => resolveServiceRef(root, "secrets/link/value", false)).toThrow(); } finally { rmSync(root, { recursive: true, force: true }); } });
test("SVC-PATH-JUNCTION", () => { const root = mkdtempSync(join(tmpdir(), "glance-path-")); try { mkdirSync(join(root, "control")); symlinkSync(tmpdir(), join(root, "control", "junction"), "junction"); expect(() => resolveServiceRef(root, "control/junction/value", false)).toThrow(); } finally { rmSync(root, { recursive: true, force: true }); } });

test("SVC-STATE-IO-NOT-ARCHIVED", () => { let archived = false; expect(() => readStateFileOrArchive("instance.json", value => value as object, { read() { throw Object.assign(new Error("denied"), { code: "EACCES" }); }, archive() { archived = true; } })).toThrow("SERVICE_IO:STATE_READ"); expect(archived).toBe(false); });
test("SVC-STATE-ARCHIVE-INCOMPATIBLE", () => { let archived = false; expect(readStateFileOrArchive("instance.json", () => { throw new Error("schema"); }, { read: () => new TextEncoder().encode("{}\n"), archive: () => { archived = true; } })).toBeNull(); expect(archived).toBe(true); });
test("SVC-STATE-REREAD-VALIDATION", () => { const root = mkdtempSync(join(tmpdir(), "glance-state-")); try { const path = join(root, "state.json"); writeDurableJson(path, globalConfig); expect(readFileSync(path, "utf8")).toBe(`${JSON.stringify(globalConfig)}\n`); } finally { rmSync(root, { recursive: true, force: true }); } });
test("SVC-SECRET-NONCE-DURABLE", () => { const fixture = createPrivateStateFixture(); try { writePrivateBytes(fixture.secretPath, fixture.secret); writePrivateBytes(fixture.noncePath, fixture.nonce); expect(readFileSync(fixture.secretPath)).toEqual(Buffer.from(fixture.secret)); expect(readFileSync(fixture.noncePath)).toEqual(Buffer.from(fixture.nonce)); fixture.assertPrivateAndDurable([fixture.secretPath, fixture.noncePath]); fixture.assertNoTemporaryResidue(); } finally { fixture.cleanup(); } });
test("SVC-STATE-DIRECTORY-FSYNC", () => { const fixture = createPrivateStateFixture(); try { const { write, events } = fixture.observePrivateWrite(); write(fixture.secretPath, fixture.secret); expect(events).toEqual(["file-fsync", "close", "rename", "directory-fsync", "reread", "remove"]); fixture.assertNoTemporaryResidue(); } finally { fixture.cleanup(); } });
test("SVC-STATE-REREAD-BYTE-DIVERGENCE", () => { const fixture = createPrivateStateFixture(); try { const { write, events } = fixture.observePrivateWrite((operation, perform) => { if (operation === "reread") writeFileSync(fixture.secretPath, new Uint8Array([0])); perform(); }); let failure: unknown; try { write(fixture.secretPath, fixture.secret); } catch (error) { failure = error; } const cause = (failure as Error).cause; expect(failure).toBeInstanceOf(ServiceIoError); expect(cause).toBeInstanceOf(Error); expect((cause as Error).message).toBe("REREAD_MISMATCH"); expect(events).toEqual(["file-fsync", "close", "rename", "directory-fsync", "reread", "remove"]); fixture.assertNoTemporaryResidue(); } finally { fixture.cleanup(); } });
test("SVC-STATE-RENAME-SUBSTITUTION-PRESERVES-REPLACEMENT", () => { const fixture = createPrivateStateFixture(), primary = new Error("rename"), replacement = new Uint8Array([9, 9]); let substituted: string | undefined; try { const { write, events } = fixture.observePrivateWrite((operation, perform, path) => { if (operation === "rename") { substituted = path; rmSync(path!, { force: true }); writeFileSync(path!, replacement); throw primary; } perform(); }); let failure: unknown; try { write(fixture.secretPath, fixture.secret); } catch (error) { failure = error; } expect((failure as Error).cause).toBe(primary); expect((failure as { cleanup: Error }).cleanup.message).toBe("PRIVATE_CLEANUP_PRESERVED"); expect(events).toEqual(["file-fsync", "close", "rename", "remove"]); expect(readFileSync(substituted!)).toEqual(Buffer.from(replacement)); } finally { fixture.cleanup(); } });
test("SVC-STATE-CLEANUP-PRESERVES-PRIMARY", () => { const fixture = createPrivateStateFixture(), primary = new Error("primary"), closeFailure = new Error("close"), removeFailure = new Error("remove"); try { const { write, events } = fixture.observePrivateWrite((operation, perform) => { if (operation === "file-fsync") throw primary; if (operation === "close") throw closeFailure; if (operation === "remove") { perform(); throw removeFailure; } perform(); }); let failure: unknown; try { write(fixture.secretPath, fixture.secret); } catch (error) { failure = error; } expect(failure).toBeInstanceOf(ServiceIoError); expect((failure as Error).cause).toBe(primary); expect((failure as { cleanup: unknown }).cleanup).toBe(closeFailure); expect(events).toEqual(["file-fsync", "close", "remove"]); fixture.assertNoTemporaryResidue(); } finally { fixture.cleanup(); } });
test("SVC-STATE-PRODUCTION-SIGNATURE", () => { const fixture = createPrivateStateFixture(), replaced: string[] = []; try { expect(writePrivateBytes.length).toBe(2); (writePrivateBytes as unknown as (path: string, bytes: Uint8Array, replacement: unknown) => void)(fixture.secretPath, fixture.secret, { fsyncFile: () => replaced.push("fsync") }); expect(replaced).toEqual([]); expect(readFileSync(fixture.secretPath)).toEqual(Buffer.from(fixture.secret)); } finally { fixture.cleanup(); } });
test("SVC-STATE-TEST-HARNESS-IS-FROZEN", () => expect(Object.isFrozen(createPrivateWriteTestHarness())).toBe(true));
test("SVC-STATE-POSIX-PRODUCTION-MODES", () => { if (process.platform === "win32") return; const fixture = createPrivateStateFixture(); try { writePrivateBytes(fixture.secretPath, fixture.secret); expect(statSync(join(fixture.root, "secrets")).mode & 0o777).toBe(0o700); expect(statSync(fixture.secretPath).mode & 0o777).toBe(0o600); } finally { fixture.cleanup(); } });
test("SVC-STATE-STRICT-INCOMPATIBLE", () => expect(() => readStateFileStrict("state.json", validateServiceConfig, { read: () => new TextEncoder().encode('{"x":1,"x":2}'), archive: () => {} })).toThrow(IncompatibleStateError));
test("SVC-STATE-IO-ERROR", () => expect(() => readStateFileStrict("state.json", validateServiceConfig, { read: () => { throw new Error("denied"); }, archive: () => {} })).toThrow(ServiceIoError));

test("SVC-PERMISSION-POSIX-DIR", () => { if (process.platform === "win32") return; const root = mkdtempSync(join(tmpdir(), "glance-perm-")); try { chmodSync(root, 0o700); assertPrivateMode(root, 0o700); } finally { rmSync(root, { recursive: true, force: true }); } });
test("SVC-PERMISSION-POSIX-FILE", () => { if (process.platform === "win32") return; const root = mkdtempSync(join(tmpdir(), "glance-perm-")), file = join(root, "private"); try { writeFileSync(file, "x", { mode: 0o600 }); assertPrivateMode(file, 0o600); } finally { rmSync(root, { recursive: true, force: true }); } });
test("SVC-PERMISSION-WINDOWS-ALLOWLIST", () => expect(() => assertWindowsAclPrivate(["CURRENT_USER", "SYSTEM"], "CURRENT_USER")).not.toThrow());
test("SVC-PERMISSION-WINDOWS-FOREIGN-PRINCIPAL", () => expect(() => assertWindowsAclPrivate(["CURRENT_USER", "EVERYONE"], "CURRENT_USER")).toThrow());
test("SVC-PERMISSION-WINDOWS-FOREIGN-SAME-BASENAME", () => expect(() => assertWindowsAclSids([{ sid: "S-1-5-21-evil", type: "allow", rights: "FA" }], "S-1-5-21-current", "S-1-5-5-1-2")).toThrow());
test("SVC-PERMISSION-WINDOWS-DENY-ACE", () => expect(() => assertWindowsAclSids([{ sid: "S-1-5-21-current", type: "deny", rights: "FA" }], "S-1-5-21-current", undefined)).toThrow());
test("SVC-PERMISSION-WINDOWS-UNEXPECTED-RIGHTS", () => expect(() => assertWindowsAclSids([{ sid: "S-1-5-21-current", type: "allow", rights: "RX" }], "S-1-5-21-current", undefined)).toThrow());
test("SVC-PERMISSION-WINDOWS-FOREIGN-LOGON-SID", () => expect(() => assertWindowsAclSids([{ sid: "S-1-5-21-current", type: "allow", rights: "FA" }, { sid: "S-1-5-18", type: "allow", rights: "FA" }, { sid: "S-1-5-5-9-9", type: "allow", rights: "0x1200a9" }], "S-1-5-21-current", "S-1-5-5-1-2")).toThrow());
test("SVC-PERMISSION-WINDOWS-UNDEFINED-LOGON-SID", () => expect(() => assertWindowsAclSids([{ sid: "S-1-5-5-1-2", type: "allow", rights: "0x1200a9" }], "S-1-5-21-current", undefined)).toThrow());
test("SVC-PERMISSION-WINDOWS-LOGON-UNEXPECTED-RIGHTS", () => expect(() => assertWindowsAclSids([{ sid: "S-1-5-5-1-2", type: "allow", rights: "FA" }], "S-1-5-21-current", "S-1-5-5-1-2")).toThrow());
test("SVC-PERMISSION-WINDOWS-EXACT-LOGON-SID", () => expect(() => assertWindowsAclSids([{ sid: "S-1-5-21-current", type: "allow", rights: "FA" }, { sid: "S-1-5-18", type: "allow", rights: "FA" }, { sid: "S-1-5-5-1-2", type: "allow", rights: "0x1200a9" }], "S-1-5-21-current", "S-1-5-5-1-2")).not.toThrow());
test("SVC-PERMISSION-FRESH-OPEN-REJECTS-EXISTING", () => { const root = mkdtempSync(join(tmpdir(), "glance-perm-")), path = join(root, "preexisting.tmp"); try { writeFileSync(path, "unchanged"); expect(() => openPrivateFreshFile(path)).toThrow("EEXIST"); expect(readFileSync(path, "utf8")).toBe("unchanged"); } finally { rmSync(root, { recursive: true, force: true }); } });
test("SVC-PERMISSION-FRESH-OPEN-RETURNS-DESCRIPTOR", () => { const root = mkdtempSync(join(tmpdir(), "glance-perm-")), path = join(root, "fresh.tmp"); let fresh: ReturnType<typeof openPrivateFreshFile> | undefined; try { fresh = openPrivateFreshFile(path); expect(Object.isFrozen(fresh.identity)).toBe(true); writeFileSync(fresh.descriptor, "x"); expect(readFileSync(path, "utf8")).toBe("x"); } finally { if (fresh) closeSync(fresh.descriptor); rmSync(root, { recursive: true, force: true }); } });
test("SVC-PERMISSION-IDENTITY-CLEANUP", () => { const root = mkdtempSync(join(tmpdir(), "glance-perm-")), ownedPath = join(root, "owned.tmp"), replacementPath = join(root, "replacement.tmp"), replacement = "replacement"; let owned: ReturnType<typeof openPrivateFreshFile> | undefined, replacementFile: ReturnType<typeof openPrivateFreshFile> | undefined; try { owned = openPrivateFreshFile(ownedPath); closeSync(owned.descriptor); expect(cleanupPrivateFreshFile(ownedPath, owned.identity)).toBe("removed"); expect(cleanupPrivateFreshFile(ownedPath, owned.identity)).toBe("absent"); replacementFile = openPrivateFreshFile(replacementPath); closeSync(replacementFile.descriptor); rmSync(replacementPath); writeFileSync(replacementPath, replacement); expect(cleanupPrivateFreshFile(replacementPath, replacementFile.identity)).toBe("preserved"); expect(readFileSync(replacementPath, "utf8")).toBe(replacement); } finally { rmSync(root, { recursive: true, force: true }); } });
test("SVC-PERMISSION-OPEN-FAILURE-PRESERVES-REPLACEMENT", () => { const root = mkdtempSync(join(tmpdir(), "glance-perm-")), path = join(root, "fresh.tmp"), replacement = "replacement", primary = new Error("after-open"); try { const harness = createPrivateFreshFileTestHarness((fresh, freshPath) => { closeSync(fresh.descriptor); rmSync(freshPath); writeFileSync(freshPath, replacement); throw primary; }); expect(Object.isFrozen(harness)).toBe(true); expect(() => harness.open(path)).toThrow(primary); expect(readFileSync(path, "utf8")).toBe(replacement); } finally { rmSync(root, { recursive: true, force: true }); } });
test("SVC-PERMISSION-GENERIC-TMP-NEVER-CAPTURES", () => { const source = readFileSync(join(import.meta.dir, "..", "lib", "glance", "service", "permissions.ts"), "utf8"); expect(source).toContain("restrictFreshFile"); expect(source).not.toContain("endsWith(\".tmp\")"); expect(restrictFile).toBeFunction(); });
test("SVC-STATE-USES-FRESH-OPEN", () => { const source = readFileSync(join(import.meta.dir, "..", "lib", "glance", "service", "state.ts"), "utf8"); expect(source).toContain("openPrivateFreshFile(temporary)"); expect(source).not.toContain("openSync(temporary"); expect(source).not.toContain("restrictFreshFile"); expect(source).not.toContain("export const privateWriteRuntime"); });
test.each(["2026-02-31T12:00:00.000Z", "2025-02-29T12:00:00.000Z", "2026-01-01T12:00:00+24:00", "2026-01-01T12:00:00+00:60"]) ("SVC-INSTANCE-TIMESTAMP rejects invalid RFC3339 %s", started_at => expect(() => validateInstance({ ...instance, started_at })).toThrow());
test.each(["2024-02-29T12:00:00.000Z", "2026-01-01T12:00:00+05:30", "2026-01-01T12:00:00-03:00"]) ("SVC-INSTANCE-TIMESTAMP accepts valid RFC3339 %s", started_at => expect(validateInstance({ ...instance, started_at }).started_at).toBe(started_at));
test("SVC-SCHEMA-EXTRACTOR-ARGS", () => { const child = Bun.spawnSync([process.execPath, join(import.meta.dir, "..", "..", "..", "scripts", "extract-glance-service-schemas.ts")], { stdout: "pipe", stderr: "pipe", timeout: 1_000 }); expect(child.exitCode).toBe(2); expect(new TextDecoder().decode(child.stdout)).toBe(""); expect(new TextDecoder().decode(child.stderr)).toBe(""); });
function schemaSource(): string { return ["config", "instance", "lock-owner", "stop-request"].map((name, index) => `### 43.${index + 1} schema\n\n\`\`\`json\n${readFileSync(join(import.meta.dir, "..", "lib", "glance", "service", "schemas", `glance-service-${name}.schema.json`), "utf8").trimEnd()}\n\`\`\``).join("\n\n"); }
function extractionIo(failures: readonly ("exists" | "mkdir" | "read" | "reread" | "write" | "rename" | "remove")[] = []): { io: SchemaExtractionIo; renamed: string[]; removes: number } { const failed = new Set(failures), files = new Map<string, string>([["spec", schemaSource()]]), renamed: string[] = []; let removes = 0; return { renamed, get removes() { return removes; }, io: { read: path => { if (failed.has("read") || (failed.has("reread") && path !== "spec") || !files.has(path)) throw new Error("READ"); return files.get(path)!; }, exists: () => { if (failed.has("exists")) throw new Error("EXISTS"); return false; }, mkdir: () => { if (failed.has("mkdir")) throw new Error("MKDIR"); }, write: (path, content) => { if (failed.has("write")) throw new Error("WRITE"); files.set(path, content); }, rename: (_from, to) => { if (failed.has("rename")) throw new Error("RENAME"); renamed.push(to); }, remove: () => { removes += 1; if (failed.has("remove")) throw new Error("REMOVE"); } } }; }
test("SVC-SCHEMA-EXTRACTOR-SPEC-MISMATCH", () => { const fixture = extractionIo(); fixture.io.read = () => "missing fences"; expect(extractGlanceServiceSchemas("spec", "out", fixture.io)).toBe(3); expect(fixture.renamed).toEqual([]); });
test.each(["exists", "mkdir", "read", "reread", "write", "rename"] as const)("SVC-SCHEMA-EXTRACTOR-%s-IO", failure => { const fixture = extractionIo([failure]); expect(extractGlanceServiceSchemas("spec", "out", fixture.io)).toBe(6); expect(fixture.renamed).toEqual([]); });
test("SVC-SCHEMA-EXTRACTOR-CLEANUP-IO", () => { const fixture = extractionIo(["write", "remove"]); expect(extractGlanceServiceSchemas("spec", "out", fixture.io)).toBe(6); expect(fixture.renamed).toEqual([]); expect(fixture.removes).toBe(1); });
test("SVC-SCHEMA-EXTRACTOR-PUBLISHES-ONLY-AFTER-REREAD", () => { const fixture = extractionIo(); expect(extractGlanceServiceSchemas("spec", "out", fixture.io)).toBe(0); expect(fixture.renamed).toEqual(["out"]); expect(fixture.removes).toBe(0); });

export const STATE_CASES = ["SVC-CONFIG-EXTRA", "SVC-CONFIG-GLOBAL-PASS", "SVC-CONFIG-GLOBAL-PROJECT", "SVC-CONFIG-HOST", "SVC-CONFIG-LIFETIME", "SVC-CONFIG-NO-OPEN", "SVC-CONFIG-PORT", "SVC-CONFIG-PROJECT-DIGEST", "SVC-CONFIG-PROJECT-LENGTH", "SVC-CONFIG-PROJECT-MISSING", "SVC-CONFIG-READ-ONLY", "SVC-CONFIG-SCHEMA-VERSION", "SVC-CONFIG-SCOPE-ENUM", "SVC-INSTANCE-CLOSED", "SVC-INSTANCE-CONFIG-DIGEST", "SVC-INSTANCE-LOG-REF", "SVC-INSTANCE-PID", "SVC-INSTANCE-PROCESS-DIGEST", "SVC-INSTANCE-REF", "SVC-INSTANCE-REQUIRED", "SVC-INSTANCE-RESTART-CLOSED", "SVC-INSTANCE-RESTART-ENUM", "SVC-INSTANCE-SECRET-DIGEST", "SVC-INSTANCE-STATE", "SVC-INSTANCE-TIMESTAMP", "SVC-INSTANCE-UUID", "SVC-PATH-ADS", "SVC-PATH-JUNCTION", "SVC-PATH-POSIX-ABS", "SVC-PATH-SYMLINK", "SVC-PATH-TRAVERSAL", "SVC-PATH-WINDOWS-ABS", "SVC-PERMISSION-POSIX-DIR", "SVC-PERMISSION-POSIX-FILE", "SVC-PERMISSION-WINDOWS-ALLOWLIST", "SVC-PERMISSION-WINDOWS-FOREIGN-PRINCIPAL", "SVC-STATE-DIRECTORY-FSYNC", "SVC-STATE-REREAD-VALIDATION"] as const;
