#!/usr/bin/env bun
// gen-json-schemas.ts — the JSON Schemas of the squad protocol, GENERATED from
// the Zod schemas that actually execute.
//
// `skills/_shared/validators/validators.ts` is the only validator any code path
// runs. Every JSON Schema beside it is documentation, and hand-written
// documentation of an executable contract drifts: `capability.schema.json`
// still capped `description` at 500 chars long after `LIMITS` raised it to
// 1500, and `skills/squads/schemas/squad-schema.json` described a v4 manifest
// nobody had authored in a year. Generating them removes the class of bug —
// the mirror cannot disagree with the source, because it IS the source.
//
//   bun scripts/gen-json-schemas.ts            write the schemas
//   bun scripts/gen-json-schemas.ts --check    fail when a file differs (check:all)
//
// `unrepresentable: "any"` is what lets a Zod construct with no JSON Schema
// equivalent (a `.refine()`, a `z.unknown()` inside a passthrough) degrade to
// `{}` instead of throwing. The alternative — dropping those fields — would
// make the mirror lie by omission.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { CapabilitySchema, SquadManifestSchema, WorkflowSchema } from "../skills/_shared/validators/validators.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "skills", "_shared", "schemas");

interface Target {
  file: string;
  schema: z.ZodType;
  id: string;
  title: string;
  description: string;
}

const TARGETS: Target[] = [
  {
    file: "capability.schema.json",
    schema: CapabilitySchema,
    id: "https://nirvana-protocol/v6/schemas/capability.schema.json",
    title: "Capability",
    description: "One entry of squad.yaml capabilities[] (Squad Protocol v5 §22, v6 §29–§31 and §33).",
  },
  {
    file: "squad.schema.json",
    schema: SquadManifestSchema,
    id: "https://nirvana-protocol/v6/schemas/squad.schema.json",
    title: "Squad manifest",
    description: "squad.yaml, the squad manifest (Squad Protocol v4 §5, v5 §22, v6 §28.6 and §34).",
  },
  {
    file: "workflow.schema.json",
    schema: WorkflowSchema,
    id: "https://nirvana-protocol/v6/schemas/workflow.schema.json",
    title: "Workflow document",
    description: "The canonical workflow graph (Squad Protocol v6 §28.1) — the frontmatter of workflows/<name>.md, as normalizeWorkflow() produces it.",
  },
];

const BANNER = "GENERATED by scripts/gen-json-schemas.ts from skills/_shared/validators/validators.ts — do not edit by hand.";

function render(t: Target): string {
  const generated = z.toJSONSchema(t.schema, { unrepresentable: "any" }) as Record<string, unknown>;
  const { $schema, ...body } = generated;
  const doc = {
    $schema: $schema ?? "https://json-schema.org/draft/2020-12/schema",
    $id: t.id,
    title: t.title,
    description: t.description,
    $comment: BANNER,
    ...body,
  };
  return JSON.stringify(doc, null, 2) + "\n";
}

const check = process.argv.includes("--check");
const drifted: string[] = [];
const written: string[] = [];

for (const t of TARGETS) {
  const path = join(OUT_DIR, t.file);
  const next = render(t);
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === next) continue;
  if (check) drifted.push(t.file);
  else { writeFileSync(path, next, "utf8"); written.push(t.file); }
}

if (check) {
  if (drifted.length) {
    console.error(`JSON SCHEMA PARITY FAILED — ${drifted.length} generated schema(s) differ from the committed file:`);
    for (const f of drifted) console.error(`  skills/_shared/schemas/${f}`);
    console.error("");
    console.error("Run `bun scripts/gen-json-schemas.ts` and commit the result.");
    process.exit(1);
  }
  console.log(`JSON schema parity OK — ${TARGETS.length} schemas match validators.ts.`);
  process.exit(0);
}

console.log(written.length
  ? `Wrote ${written.length} schema(s): ${written.join(", ")}`
  : `Up to date — ${TARGETS.length} schemas already match validators.ts.`);
